# Generated by Django 6.0.6 on 2026-09-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
